---
- hosts: localhost
  become: yes
 
  tasks:
 - name: Install packages
    apt:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
      force_apt_get: true
    vars:
      packages:
      - sqlite3
      - npm
      - nodejs
      - git
    
